// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcwQc1erBSu3HE93D9Sbr8wt0UAL7_I6U',
    appId: '1:104514464614:web:59b36f8726b365e3e376a7',
    messagingSenderId: '104514464614',
    projectId: 'logistix-ffc31',
    authDomain: 'logistix-ffc31.firebaseapp.com',
    storageBucket: 'logistix-ffc31.appspot.com',
    measurementId: 'G-CP0J43LFXD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3Z_i38Pn0lAyS_3ZH7p0LvuTDeSikIlQ',
    appId: '1:104514464614:android:c9bba7dd19de1354e376a7',
    messagingSenderId: '104514464614',
    projectId: 'logistix-ffc31',
    storageBucket: 'logistix-ffc31.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPa7lYhCuQGk4EVYKO86SPnSYA90RAp98',
    appId: '1:104514464614:ios:e2a38145b36ed07ee376a7',
    messagingSenderId: '104514464614',
    projectId: 'logistix-ffc31',
    storageBucket: 'logistix-ffc31.appspot.com',
    iosClientId: '104514464614-5phugcaamkht4lshag200861v3utm3d5.apps.googleusercontent.com',
    iosBundleId: 'com.logistix.logistix',
  );
}
